"""
Rainbow color theme presets for the Notes Overlay application.
"""
from typing import Dict, List


class ThemePresets:
    """Collection of pre-built theme presets."""
    
    PRESETS: List[Dict] = [
        # Default Light
        {
            "id": "default_light",
            "name": "Default Light",
            "category": "Default",
            "mode": "light",
            "window_bg": "#f5f5f5",
            "window_bg_opacity": 240,
            "text_primary": "#000000",
            "text_secondary": "#666666",
            "border_color": "#c8c8c8",
            "window_border_color": "#c8c8c8",
            "accent_color": "#0078d7",
            "title_bar_color": "#f5f5f5",
            "tab_bg_active": "#f5f5f5",
            "tab_bg_inactive": "#e6e6e6",
            "tab_text_color": "#000000",
            "scrollbar_color": "#b4b4b4",
            "button_bg": "#f0f0f0",
            "button_text": "#000000",
            "button_hover": "#e0e0e0",
            "button_border": "#c8c8c8",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 10,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Default Dark
        {
            "id": "default_dark",
            "name": "Default Dark",
            "category": "Default",
            "mode": "dark",
            "window_bg": "#202020",
            "window_bg_opacity": 240,
            "text_primary": "#ffffff",
            "text_secondary": "#b3b3b3",
            "border_color": "#646464",
            "window_border_color": "#646464",
            "accent_color": "#0078d7",
            "title_bar_color": "#202020",
            "tab_bg_active": "#202020",
            "tab_bg_inactive": "#323232",
            "tab_text_color": "#ffffff",
            "scrollbar_color": "#646464",
            "button_bg": "#3c3c3c",
            "button_text": "#ffffff",
            "button_hover": "#505050",
            "button_border": "#646464",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 10,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Red - Light "Coral Blush"
        {
            "id": "red_light",
            "name": "Coral Blush",
            "category": "Red",
            "mode": "light",
            "window_bg": "#FFE5E5",
            "window_bg_opacity": 240,
            "text_primary": "#8B0000",
            "text_secondary": "#CD5C5C",
            "border_color": "#FFB3BA",
            "window_border_color": "#FFB3BA",
            "accent_color": "#FF6B6B",
            "title_bar_color": "#FFCCCC",
            "tab_bg_active": "#FFA07A",
            "tab_bg_inactive": "#FFD6D6",
            "tab_text_color": "#8B0000",
            "scrollbar_color": "#FF6B6B",
            "button_bg": "#FF4444",
            "button_text": "#FFFFFF",
            "button_hover": "#FF6666",
            "button_border": "#CC0000",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Red - Dark "Crimson Night"
        {
            "id": "red_dark",
            "name": "Crimson Night",
            "category": "Red",
            "mode": "dark",
            "window_bg": "#2D1B1B",
            "window_bg_opacity": 240,
            "text_primary": "#FFB3BA",
            "text_secondary": "#FF8A8A",
            "border_color": "#8B1A1A",
            "window_border_color": "#8B1A1A",
            "accent_color": "#FF3333",
            "title_bar_color": "#3D1F1F",
            "tab_bg_active": "#8B1A1A",
            "tab_bg_inactive": "#4D2B2B",
            "tab_text_color": "#FFB3BA",
            "scrollbar_color": "#DC143C",
            "button_bg": "#DC143C",
            "button_text": "#FFFFFF",
            "button_hover": "#FF3333",
            "button_border": "#8B0000",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Orange - Light "Sunset Glow"
        {
            "id": "orange_light",
            "name": "Sunset Glow",
            "category": "Orange",
            "mode": "light",
            "window_bg": "#FFF0E5",
            "window_bg_opacity": 240,
            "text_primary": "#5C3A21",
            "text_secondary": "#CC5500",
            "border_color": "#FFB366",
            "window_border_color": "#FFB366",
            "accent_color": "#FF8C42",
            "title_bar_color": "#FFE0CC",
            "tab_bg_active": "#FFB366",
            "tab_bg_inactive": "#FFE5CC",
            "tab_text_color": "#5C3A21",
            "scrollbar_color": "#FF8C42",
            "button_bg": "#FF7F00",
            "button_text": "#FFFFFF",
            "button_hover": "#FF9500",
            "button_border": "#CC6600",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Orange - Dark "Ember"
        {
            "id": "orange_dark",
            "name": "Ember",
            "category": "Orange",
            "mode": "dark",
            "window_bg": "#2D1F1B",
            "window_bg_opacity": 240,
            "text_primary": "#FFCC99",
            "text_secondary": "#FFB380",
            "border_color": "#8B4513",
            "window_border_color": "#8B4513",
            "accent_color": "#FF9500",
            "title_bar_color": "#3D2F1F",
            "tab_bg_active": "#8B4513",
            "tab_bg_inactive": "#4D3F2F",
            "tab_text_color": "#FFCC99",
            "scrollbar_color": "#FF8C00",
            "button_bg": "#FF8C00",
            "button_text": "#FFFFFF",
            "button_hover": "#FF9500",
            "button_border": "#CC6600",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Yellow - Light "Sunshine"
        {
            "id": "yellow_light",
            "name": "Sunshine",
            "category": "Yellow",
            "mode": "light",
            "window_bg": "#FFFAEB",
            "window_bg_opacity": 240,
            "text_primary": "#4A4A1F",
            "text_secondary": "#B8860B",
            "border_color": "#FFEB99",
            "window_border_color": "#FFEB99",
            "accent_color": "#FFD700",
            "title_bar_color": "#FFF8DC",
            "tab_bg_active": "#FFEB99",
            "tab_bg_inactive": "#FFFACD",
            "tab_text_color": "#4A4A1F",
            "scrollbar_color": "#FFD700",
            "button_bg": "#FFC800",
            "button_text": "#000000",
            "button_hover": "#FFD700",
            "button_border": "#CC9900",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Yellow - Dark "Golden Hour"
        {
            "id": "yellow_dark",
            "name": "Golden Hour",
            "category": "Yellow",
            "mode": "dark",
            "window_bg": "#2D2A1B",
            "window_bg_opacity": 240,
            "text_primary": "#FFF8DC",
            "text_secondary": "#FFEB8F",
            "border_color": "#B8860B",
            "window_border_color": "#B8860B",
            "accent_color": "#FFD700",
            "title_bar_color": "#3D3A2B",
            "tab_bg_active": "#B8860B",
            "tab_bg_inactive": "#4D4A3B",
            "tab_text_color": "#FFF8DC",
            "scrollbar_color": "#FFBF00",
            "button_bg": "#FFBF00",
            "button_text": "#000000",
            "button_hover": "#FFD700",
            "button_border": "#B8860B",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Green - Light "Mint Fresh"
        {
            "id": "green_light",
            "name": "Mint Fresh",
            "category": "Green",
            "mode": "light",
            "window_bg": "#E8F8F5",
            "window_bg_opacity": 240,
            "text_primary": "#1B4D3E",
            "text_secondary": "#2E8B57",
            "border_color": "#B2E6D4",
            "window_border_color": "#B2E6D4",
            "accent_color": "#00C853",
            "title_bar_color": "#C8E6C9",
            "tab_bg_active": "#B2E6D4",
            "tab_bg_inactive": "#D4EDDA",
            "tab_text_color": "#1B4D3E",
            "scrollbar_color": "#00C853",
            "button_bg": "#00E676",
            "button_text": "#FFFFFF",
            "button_hover": "#00C853",
            "button_border": "#009624",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Green - Dark "Forest Night"
        {
            "id": "green_dark",
            "name": "Forest Night",
            "category": "Green",
            "mode": "dark",
            "window_bg": "#1B2D1F",
            "window_bg_opacity": 240,
            "text_primary": "#C1F0E0",
            "text_secondary": "#90EE90",
            "border_color": "#1E4D2B",
            "window_border_color": "#1E4D2B",
            "accent_color": "#00FF7F",
            "title_bar_color": "#2D3D2F",
            "tab_bg_active": "#1E4D2B",
            "tab_bg_inactive": "#2D4D3F",
            "tab_text_color": "#C1F0E0",
            "scrollbar_color": "#32CD32",
            "button_bg": "#32CD32",
            "button_text": "#FFFFFF",
            "button_hover": "#00FF7F",
            "button_border": "#1E8B3D",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Blue - Light "Sky"
        {
            "id": "blue_light",
            "name": "Sky",
            "category": "Blue",
            "mode": "light",
            "window_bg": "#E6F3FF",
            "window_bg_opacity": 240,
            "text_primary": "#1A2A4D",
            "text_secondary": "#2E5C8A",
            "border_color": "#87CEEB",
            "window_border_color": "#87CEEB",
            "accent_color": "#0080FF",
            "title_bar_color": "#B3D9FF",
            "tab_bg_active": "#87CEEB",
            "tab_bg_inactive": "#CCE5FF",
            "tab_text_color": "#1A2A4D",
            "scrollbar_color": "#0080FF",
            "button_bg": "#1E90FF",
            "button_text": "#FFFFFF",
            "button_hover": "#0080FF",
            "button_border": "#0066CC",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Blue - Dark "Midnight"
        {
            "id": "blue_dark",
            "name": "Midnight",
            "category": "Blue",
            "mode": "dark",
            "window_bg": "#1B1F2D",
            "window_bg_opacity": 240,
            "text_primary": "#B3D9FF",
            "text_secondary": "#87CEEB",
            "border_color": "#1E3A5F",
            "window_border_color": "#1E3A5F",
            "accent_color": "#00BFFF",
            "title_bar_color": "#2B2F3D",
            "tab_bg_active": "#1E3A5F",
            "tab_bg_inactive": "#2D3F5F",
            "tab_text_color": "#B3D9FF",
            "scrollbar_color": "#0099FF",
            "button_bg": "#0099FF",
            "button_text": "#FFFFFF",
            "button_hover": "#00BFFF",
            "button_border": "#0066CC",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Indigo - Light "Lavender Mist"
        {
            "id": "indigo_light",
            "name": "Lavender Mist",
            "category": "Indigo",
            "mode": "light",
            "window_bg": "#EDE7F6",
            "window_bg_opacity": 240,
            "text_primary": "#311B92",
            "text_secondary": "#5E35B1",
            "border_color": "#C5CAE9",
            "window_border_color": "#C5CAE9",
            "accent_color": "#5C6BC0",
            "title_bar_color": "#D1C4E9",
            "tab_bg_active": "#C5CAE9",
            "tab_bg_inactive": "#E1BEE7",
            "tab_text_color": "#311B92",
            "scrollbar_color": "#5C6BC0",
            "button_bg": "#4A5FBC",
            "button_text": "#FFFFFF",
            "button_hover": "#5C6BC0",
            "button_border": "#3F51B5",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Indigo - Dark "Twilight"
        {
            "id": "indigo_dark",
            "name": "Twilight",
            "category": "Indigo",
            "mode": "dark",
            "window_bg": "#1F1B2D",
            "window_bg_opacity": 240,
            "text_primary": "#D1C4E9",
            "text_secondary": "#B39DDB",
            "border_color": "#4527A0",
            "window_border_color": "#4527A0",
            "accent_color": "#7C4DFF",
            "title_bar_color": "#2F2B3D",
            "tab_bg_active": "#4527A0",
            "tab_bg_inactive": "#3F2F4D",
            "tab_text_color": "#D1C4E9",
            "scrollbar_color": "#651FFF",
            "button_bg": "#651FFF",
            "button_text": "#FFFFFF",
            "button_hover": "#7C4DFF",
            "button_border": "#4527A0",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Violet - Light "Orchid Bloom"
        {
            "id": "violet_light",
            "name": "Orchid Bloom",
            "category": "Violet",
            "mode": "light",
            "window_bg": "#F3E5F5",
            "window_bg_opacity": 240,
            "text_primary": "#4A148C",
            "text_secondary": "#7B1FA2",
            "border_color": "#E1BEE7",
            "window_border_color": "#E1BEE7",
            "accent_color": "#E040FB",
            "title_bar_color": "#F8BBD9",
            "tab_bg_active": "#E1BEE7",
            "tab_bg_inactive": "#F3E5F5",
            "tab_text_color": "#4A148C",
            "scrollbar_color": "#E040FB",
            "button_bg": "#9C27B0",
            "button_text": "#FFFFFF",
            "button_hover": "#E040FB",
            "button_border": "#7B1FA2",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
        
        # Violet - Dark "Amethyst Night"
        {
            "id": "violet_dark",
            "name": "Amethyst Night",
            "category": "Violet",
            "mode": "dark",
            "window_bg": "#2D1B33",
            "window_bg_opacity": 240,
            "text_primary": "#E1BEE7",
            "text_secondary": "#CE93D8",
            "border_color": "#6A1B9A",
            "window_border_color": "#6A1B9A",
            "accent_color": "#D500F9",
            "title_bar_color": "#3D2B43",
            "tab_bg_active": "#6A1B9A",
            "tab_bg_inactive": "#4D2B5D",
            "tab_text_color": "#E1BEE7",
            "scrollbar_color": "#AA00FF",
            "button_bg": "#AA00FF",
            "button_text": "#FFFFFF",
            "button_hover": "#D500F9",
            "button_border": "#6A1B9A",
            "window_opacity": 95,
            "blur_enabled": True,
            "blur_intensity": 8,
            "shadow_intensity": 3,
            "border_radius": 12,
            "font_family": "Segoe UI",
            "font_size": 11,
        },
    ]
    
    @classmethod
    def get_all_presets(cls) -> List[Dict]:
        """Get all theme presets."""
        return cls.PRESETS.copy()
    
    @classmethod
    def get_preset_by_id(cls, preset_id: str) -> Dict:
        """Get a specific preset by ID."""
        for preset in cls.PRESETS:
            if preset["id"] == preset_id:
                return preset.copy()
        return None
    
    @classmethod
    def get_presets_by_category(cls, category: str) -> List[Dict]:
        """Get all presets in a category."""
        return [p.copy() for p in cls.PRESETS if p["category"] == category]
    
    @classmethod
    def get_categories(cls) -> List[str]:
        """Get all unique categories."""
        categories = []
        for preset in cls.PRESETS:
            if preset["category"] not in categories:
                categories.append(preset["category"])
        return categories

